package com.loon.mybatis.core.pojo;

public class CmdBusiness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_id
     *
     * @mbggenerated
     */
    private Integer busiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_clm_id
     *
     * @mbggenerated
     */
    private String busiClmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_no
     *
     * @mbggenerated
     */
    private String busiNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_name
     *
     * @mbggenerated
     */
    private String busiApplName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_addr
     *
     * @mbggenerated
     */
    private String busiApplAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_sex
     *
     * @mbggenerated
     */
    private String busiApplSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_id_type
     *
     * @mbggenerated
     */
    private String busiApplIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_id_start_date
     *
     * @mbggenerated
     */
    private String busiApplIdStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_id_end_date
     *
     * @mbggenerated
     */
    private String busiApplIdEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_birthday
     *
     * @mbggenerated
     */
    private String busiApplBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_date
     *
     * @mbggenerated
     */
    private String busiApplDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_id_no
     *
     * @mbggenerated
     */
    private String busiApplIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_rel
     *
     * @mbggenerated
     */
    private String busiApplRel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_mobile
     *
     * @mbggenerated
     */
    private String busiMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_appl_type
     *
     * @mbggenerated
     */
    private String busiApplType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_phone
     *
     * @mbggenerated
     */
    private String busiPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_pay_mode
     *
     * @mbggenerated
     */
    private String busiPayMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_patient_name
     *
     * @mbggenerated
     */
    private String busiPatientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_date
     *
     * @mbggenerated
     */
    private String busiAcciDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_result
     *
     * @mbggenerated
     */
    private String busiAcciResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acc_no
     *
     * @mbggenerated
     */
    private String busiAccNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acc_name
     *
     * @mbggenerated
     */
    private String busiAccName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acc_id_no
     *
     * @mbggenerated
     */
    private String busiAccIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_bank_code
     *
     * @mbggenerated
     */
    private String busiBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_pfund_amo
     *
     * @mbggenerated
     */
    private String busiPfundAmo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_else_ded_amo
     *
     * @mbggenerated
     */
    private String busiElseDedAmo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_medicare_type
     *
     * @mbggenerated
     */
    private String busiMedicareType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_cause_name
     *
     * @mbggenerated
     */
    private String busiAcciCauseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_cause
     *
     * @mbggenerated
     */
    private String busiAcciCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_code
     *
     * @mbggenerated
     */
    private String busiAcciCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_name
     *
     * @mbggenerated
     */
    private String busiAcciName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_confirm_date
     *
     * @mbggenerated
     */
    private String busiConfirmDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_detail_addr
     *
     * @mbggenerated
     */
    private String busiAcciDetailAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_rec_date
     *
     * @mbggenerated
     */
    private String busiRecDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_ass_name
     *
     * @mbggenerated
     */
    private String busiAssName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_ass_phone
     *
     * @mbggenerated
     */
    private String busiAssPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_is_ass
     *
     * @mbggenerated
     */
    private String busiIsAss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_prov
     *
     * @mbggenerated
     */
    private String busiAcciProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_city
     *
     * @mbggenerated
     */
    private String busiAcciCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_dist
     *
     * @mbggenerated
     */
    private String busiAcciDist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_street
     *
     * @mbggenerated
     */
    private String busiAcciStreet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_id_no
     *
     * @mbggenerated
     */
    private String busiAcciIdNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_id_type
     *
     * @mbggenerated
     */
    private String busiAcciIdType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_sex
     *
     * @mbggenerated
     */
    private String busiAcciSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_id_start_date
     *
     * @mbggenerated
     */
    private String busiAcciIdStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_id_end_date
     *
     * @mbggenerated
     */
    private String busiAcciIdEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_birthday
     *
     * @mbggenerated
     */
    private String busiAcciBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_acci_payee_rel
     *
     * @mbggenerated
     */
    private String busiAcciPayeeRel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_type
     *
     * @mbggenerated
     */
    private String busiType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_properties_remark
     *
     * @mbggenerated
     */
    private String busiPropertiesRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_dg_bytes
     *
     * @mbggenerated
     */
    private String busiDgBytes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_medical_insurance
     *
     * @mbggenerated
     */
    private String busiMedicalInsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_batch_no
     *
     * @mbggenerated
     */
    private String busiBatchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cmd_Business.busi_branch_no
     *
     * @mbggenerated
     */
    private String busiBranchNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_id
     *
     * @return the value of cmd_Business.busi_id
     *
     * @mbggenerated
     */
    public Integer getBusiId() {
        return busiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_id
     *
     * @param busiId the value for cmd_Business.busi_id
     *
     * @mbggenerated
     */
    public void setBusiId(Integer busiId) {
        this.busiId = busiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_clm_id
     *
     * @return the value of cmd_Business.busi_clm_id
     *
     * @mbggenerated
     */
    public String getBusiClmId() {
        return busiClmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_clm_id
     *
     * @param busiClmId the value for cmd_Business.busi_clm_id
     *
     * @mbggenerated
     */
    public void setBusiClmId(String busiClmId) {
        this.busiClmId = busiClmId == null ? null : busiClmId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_no
     *
     * @return the value of cmd_Business.busi_no
     *
     * @mbggenerated
     */
    public String getBusiNo() {
        return busiNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_no
     *
     * @param busiNo the value for cmd_Business.busi_no
     *
     * @mbggenerated
     */
    public void setBusiNo(String busiNo) {
        this.busiNo = busiNo == null ? null : busiNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_name
     *
     * @return the value of cmd_Business.busi_appl_name
     *
     * @mbggenerated
     */
    public String getBusiApplName() {
        return busiApplName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_name
     *
     * @param busiApplName the value for cmd_Business.busi_appl_name
     *
     * @mbggenerated
     */
    public void setBusiApplName(String busiApplName) {
        this.busiApplName = busiApplName == null ? null : busiApplName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_addr
     *
     * @return the value of cmd_Business.busi_appl_addr
     *
     * @mbggenerated
     */
    public String getBusiApplAddr() {
        return busiApplAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_addr
     *
     * @param busiApplAddr the value for cmd_Business.busi_appl_addr
     *
     * @mbggenerated
     */
    public void setBusiApplAddr(String busiApplAddr) {
        this.busiApplAddr = busiApplAddr == null ? null : busiApplAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_sex
     *
     * @return the value of cmd_Business.busi_appl_sex
     *
     * @mbggenerated
     */
    public String getBusiApplSex() {
        return busiApplSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_sex
     *
     * @param busiApplSex the value for cmd_Business.busi_appl_sex
     *
     * @mbggenerated
     */
    public void setBusiApplSex(String busiApplSex) {
        this.busiApplSex = busiApplSex == null ? null : busiApplSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_id_type
     *
     * @return the value of cmd_Business.busi_appl_id_type
     *
     * @mbggenerated
     */
    public String getBusiApplIdType() {
        return busiApplIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_id_type
     *
     * @param busiApplIdType the value for cmd_Business.busi_appl_id_type
     *
     * @mbggenerated
     */
    public void setBusiApplIdType(String busiApplIdType) {
        this.busiApplIdType = busiApplIdType == null ? null : busiApplIdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_id_start_date
     *
     * @return the value of cmd_Business.busi_appl_id_start_date
     *
     * @mbggenerated
     */
    public String getBusiApplIdStartDate() {
        return busiApplIdStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_id_start_date
     *
     * @param busiApplIdStartDate the value for cmd_Business.busi_appl_id_start_date
     *
     * @mbggenerated
     */
    public void setBusiApplIdStartDate(String busiApplIdStartDate) {
        this.busiApplIdStartDate = busiApplIdStartDate == null ? null : busiApplIdStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_id_end_date
     *
     * @return the value of cmd_Business.busi_appl_id_end_date
     *
     * @mbggenerated
     */
    public String getBusiApplIdEndDate() {
        return busiApplIdEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_id_end_date
     *
     * @param busiApplIdEndDate the value for cmd_Business.busi_appl_id_end_date
     *
     * @mbggenerated
     */
    public void setBusiApplIdEndDate(String busiApplIdEndDate) {
        this.busiApplIdEndDate = busiApplIdEndDate == null ? null : busiApplIdEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_birthday
     *
     * @return the value of cmd_Business.busi_appl_birthday
     *
     * @mbggenerated
     */
    public String getBusiApplBirthday() {
        return busiApplBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_birthday
     *
     * @param busiApplBirthday the value for cmd_Business.busi_appl_birthday
     *
     * @mbggenerated
     */
    public void setBusiApplBirthday(String busiApplBirthday) {
        this.busiApplBirthday = busiApplBirthday == null ? null : busiApplBirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_date
     *
     * @return the value of cmd_Business.busi_appl_date
     *
     * @mbggenerated
     */
    public String getBusiApplDate() {
        return busiApplDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_date
     *
     * @param busiApplDate the value for cmd_Business.busi_appl_date
     *
     * @mbggenerated
     */
    public void setBusiApplDate(String busiApplDate) {
        this.busiApplDate = busiApplDate == null ? null : busiApplDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_id_no
     *
     * @return the value of cmd_Business.busi_appl_id_no
     *
     * @mbggenerated
     */
    public String getBusiApplIdNo() {
        return busiApplIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_id_no
     *
     * @param busiApplIdNo the value for cmd_Business.busi_appl_id_no
     *
     * @mbggenerated
     */
    public void setBusiApplIdNo(String busiApplIdNo) {
        this.busiApplIdNo = busiApplIdNo == null ? null : busiApplIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_rel
     *
     * @return the value of cmd_Business.busi_appl_rel
     *
     * @mbggenerated
     */
    public String getBusiApplRel() {
        return busiApplRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_rel
     *
     * @param busiApplRel the value for cmd_Business.busi_appl_rel
     *
     * @mbggenerated
     */
    public void setBusiApplRel(String busiApplRel) {
        this.busiApplRel = busiApplRel == null ? null : busiApplRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_mobile
     *
     * @return the value of cmd_Business.busi_mobile
     *
     * @mbggenerated
     */
    public String getBusiMobile() {
        return busiMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_mobile
     *
     * @param busiMobile the value for cmd_Business.busi_mobile
     *
     * @mbggenerated
     */
    public void setBusiMobile(String busiMobile) {
        this.busiMobile = busiMobile == null ? null : busiMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_appl_type
     *
     * @return the value of cmd_Business.busi_appl_type
     *
     * @mbggenerated
     */
    public String getBusiApplType() {
        return busiApplType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_appl_type
     *
     * @param busiApplType the value for cmd_Business.busi_appl_type
     *
     * @mbggenerated
     */
    public void setBusiApplType(String busiApplType) {
        this.busiApplType = busiApplType == null ? null : busiApplType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_phone
     *
     * @return the value of cmd_Business.busi_phone
     *
     * @mbggenerated
     */
    public String getBusiPhone() {
        return busiPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_phone
     *
     * @param busiPhone the value for cmd_Business.busi_phone
     *
     * @mbggenerated
     */
    public void setBusiPhone(String busiPhone) {
        this.busiPhone = busiPhone == null ? null : busiPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_pay_mode
     *
     * @return the value of cmd_Business.busi_pay_mode
     *
     * @mbggenerated
     */
    public String getBusiPayMode() {
        return busiPayMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_pay_mode
     *
     * @param busiPayMode the value for cmd_Business.busi_pay_mode
     *
     * @mbggenerated
     */
    public void setBusiPayMode(String busiPayMode) {
        this.busiPayMode = busiPayMode == null ? null : busiPayMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_patient_name
     *
     * @return the value of cmd_Business.busi_patient_name
     *
     * @mbggenerated
     */
    public String getBusiPatientName() {
        return busiPatientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_patient_name
     *
     * @param busiPatientName the value for cmd_Business.busi_patient_name
     *
     * @mbggenerated
     */
    public void setBusiPatientName(String busiPatientName) {
        this.busiPatientName = busiPatientName == null ? null : busiPatientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_date
     *
     * @return the value of cmd_Business.busi_acci_date
     *
     * @mbggenerated
     */
    public String getBusiAcciDate() {
        return busiAcciDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_date
     *
     * @param busiAcciDate the value for cmd_Business.busi_acci_date
     *
     * @mbggenerated
     */
    public void setBusiAcciDate(String busiAcciDate) {
        this.busiAcciDate = busiAcciDate == null ? null : busiAcciDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_result
     *
     * @return the value of cmd_Business.busi_acci_result
     *
     * @mbggenerated
     */
    public String getBusiAcciResult() {
        return busiAcciResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_result
     *
     * @param busiAcciResult the value for cmd_Business.busi_acci_result
     *
     * @mbggenerated
     */
    public void setBusiAcciResult(String busiAcciResult) {
        this.busiAcciResult = busiAcciResult == null ? null : busiAcciResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acc_no
     *
     * @return the value of cmd_Business.busi_acc_no
     *
     * @mbggenerated
     */
    public String getBusiAccNo() {
        return busiAccNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acc_no
     *
     * @param busiAccNo the value for cmd_Business.busi_acc_no
     *
     * @mbggenerated
     */
    public void setBusiAccNo(String busiAccNo) {
        this.busiAccNo = busiAccNo == null ? null : busiAccNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acc_name
     *
     * @return the value of cmd_Business.busi_acc_name
     *
     * @mbggenerated
     */
    public String getBusiAccName() {
        return busiAccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acc_name
     *
     * @param busiAccName the value for cmd_Business.busi_acc_name
     *
     * @mbggenerated
     */
    public void setBusiAccName(String busiAccName) {
        this.busiAccName = busiAccName == null ? null : busiAccName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acc_id_no
     *
     * @return the value of cmd_Business.busi_acc_id_no
     *
     * @mbggenerated
     */
    public String getBusiAccIdNo() {
        return busiAccIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acc_id_no
     *
     * @param busiAccIdNo the value for cmd_Business.busi_acc_id_no
     *
     * @mbggenerated
     */
    public void setBusiAccIdNo(String busiAccIdNo) {
        this.busiAccIdNo = busiAccIdNo == null ? null : busiAccIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_bank_code
     *
     * @return the value of cmd_Business.busi_bank_code
     *
     * @mbggenerated
     */
    public String getBusiBankCode() {
        return busiBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_bank_code
     *
     * @param busiBankCode the value for cmd_Business.busi_bank_code
     *
     * @mbggenerated
     */
    public void setBusiBankCode(String busiBankCode) {
        this.busiBankCode = busiBankCode == null ? null : busiBankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_pfund_amo
     *
     * @return the value of cmd_Business.busi_pfund_amo
     *
     * @mbggenerated
     */
    public String getBusiPfundAmo() {
        return busiPfundAmo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_pfund_amo
     *
     * @param busiPfundAmo the value for cmd_Business.busi_pfund_amo
     *
     * @mbggenerated
     */
    public void setBusiPfundAmo(String busiPfundAmo) {
        this.busiPfundAmo = busiPfundAmo == null ? null : busiPfundAmo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_else_ded_amo
     *
     * @return the value of cmd_Business.busi_else_ded_amo
     *
     * @mbggenerated
     */
    public String getBusiElseDedAmo() {
        return busiElseDedAmo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_else_ded_amo
     *
     * @param busiElseDedAmo the value for cmd_Business.busi_else_ded_amo
     *
     * @mbggenerated
     */
    public void setBusiElseDedAmo(String busiElseDedAmo) {
        this.busiElseDedAmo = busiElseDedAmo == null ? null : busiElseDedAmo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_medicare_type
     *
     * @return the value of cmd_Business.busi_medicare_type
     *
     * @mbggenerated
     */
    public String getBusiMedicareType() {
        return busiMedicareType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_medicare_type
     *
     * @param busiMedicareType the value for cmd_Business.busi_medicare_type
     *
     * @mbggenerated
     */
    public void setBusiMedicareType(String busiMedicareType) {
        this.busiMedicareType = busiMedicareType == null ? null : busiMedicareType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_cause_name
     *
     * @return the value of cmd_Business.busi_acci_cause_name
     *
     * @mbggenerated
     */
    public String getBusiAcciCauseName() {
        return busiAcciCauseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_cause_name
     *
     * @param busiAcciCauseName the value for cmd_Business.busi_acci_cause_name
     *
     * @mbggenerated
     */
    public void setBusiAcciCauseName(String busiAcciCauseName) {
        this.busiAcciCauseName = busiAcciCauseName == null ? null : busiAcciCauseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_cause
     *
     * @return the value of cmd_Business.busi_acci_cause
     *
     * @mbggenerated
     */
    public String getBusiAcciCause() {
        return busiAcciCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_cause
     *
     * @param busiAcciCause the value for cmd_Business.busi_acci_cause
     *
     * @mbggenerated
     */
    public void setBusiAcciCause(String busiAcciCause) {
        this.busiAcciCause = busiAcciCause == null ? null : busiAcciCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_code
     *
     * @return the value of cmd_Business.busi_acci_code
     *
     * @mbggenerated
     */
    public String getBusiAcciCode() {
        return busiAcciCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_code
     *
     * @param busiAcciCode the value for cmd_Business.busi_acci_code
     *
     * @mbggenerated
     */
    public void setBusiAcciCode(String busiAcciCode) {
        this.busiAcciCode = busiAcciCode == null ? null : busiAcciCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_name
     *
     * @return the value of cmd_Business.busi_acci_name
     *
     * @mbggenerated
     */
    public String getBusiAcciName() {
        return busiAcciName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_name
     *
     * @param busiAcciName the value for cmd_Business.busi_acci_name
     *
     * @mbggenerated
     */
    public void setBusiAcciName(String busiAcciName) {
        this.busiAcciName = busiAcciName == null ? null : busiAcciName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_confirm_date
     *
     * @return the value of cmd_Business.busi_confirm_date
     *
     * @mbggenerated
     */
    public String getBusiConfirmDate() {
        return busiConfirmDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_confirm_date
     *
     * @param busiConfirmDate the value for cmd_Business.busi_confirm_date
     *
     * @mbggenerated
     */
    public void setBusiConfirmDate(String busiConfirmDate) {
        this.busiConfirmDate = busiConfirmDate == null ? null : busiConfirmDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_detail_addr
     *
     * @return the value of cmd_Business.busi_acci_detail_addr
     *
     * @mbggenerated
     */
    public String getBusiAcciDetailAddr() {
        return busiAcciDetailAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_detail_addr
     *
     * @param busiAcciDetailAddr the value for cmd_Business.busi_acci_detail_addr
     *
     * @mbggenerated
     */
    public void setBusiAcciDetailAddr(String busiAcciDetailAddr) {
        this.busiAcciDetailAddr = busiAcciDetailAddr == null ? null : busiAcciDetailAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_rec_date
     *
     * @return the value of cmd_Business.busi_rec_date
     *
     * @mbggenerated
     */
    public String getBusiRecDate() {
        return busiRecDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_rec_date
     *
     * @param busiRecDate the value for cmd_Business.busi_rec_date
     *
     * @mbggenerated
     */
    public void setBusiRecDate(String busiRecDate) {
        this.busiRecDate = busiRecDate == null ? null : busiRecDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_ass_name
     *
     * @return the value of cmd_Business.busi_ass_name
     *
     * @mbggenerated
     */
    public String getBusiAssName() {
        return busiAssName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_ass_name
     *
     * @param busiAssName the value for cmd_Business.busi_ass_name
     *
     * @mbggenerated
     */
    public void setBusiAssName(String busiAssName) {
        this.busiAssName = busiAssName == null ? null : busiAssName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_ass_phone
     *
     * @return the value of cmd_Business.busi_ass_phone
     *
     * @mbggenerated
     */
    public String getBusiAssPhone() {
        return busiAssPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_ass_phone
     *
     * @param busiAssPhone the value for cmd_Business.busi_ass_phone
     *
     * @mbggenerated
     */
    public void setBusiAssPhone(String busiAssPhone) {
        this.busiAssPhone = busiAssPhone == null ? null : busiAssPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_is_ass
     *
     * @return the value of cmd_Business.busi_is_ass
     *
     * @mbggenerated
     */
    public String getBusiIsAss() {
        return busiIsAss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_is_ass
     *
     * @param busiIsAss the value for cmd_Business.busi_is_ass
     *
     * @mbggenerated
     */
    public void setBusiIsAss(String busiIsAss) {
        this.busiIsAss = busiIsAss == null ? null : busiIsAss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_prov
     *
     * @return the value of cmd_Business.busi_acci_prov
     *
     * @mbggenerated
     */
    public String getBusiAcciProv() {
        return busiAcciProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_prov
     *
     * @param busiAcciProv the value for cmd_Business.busi_acci_prov
     *
     * @mbggenerated
     */
    public void setBusiAcciProv(String busiAcciProv) {
        this.busiAcciProv = busiAcciProv == null ? null : busiAcciProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_city
     *
     * @return the value of cmd_Business.busi_acci_city
     *
     * @mbggenerated
     */
    public String getBusiAcciCity() {
        return busiAcciCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_city
     *
     * @param busiAcciCity the value for cmd_Business.busi_acci_city
     *
     * @mbggenerated
     */
    public void setBusiAcciCity(String busiAcciCity) {
        this.busiAcciCity = busiAcciCity == null ? null : busiAcciCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_dist
     *
     * @return the value of cmd_Business.busi_acci_dist
     *
     * @mbggenerated
     */
    public String getBusiAcciDist() {
        return busiAcciDist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_dist
     *
     * @param busiAcciDist the value for cmd_Business.busi_acci_dist
     *
     * @mbggenerated
     */
    public void setBusiAcciDist(String busiAcciDist) {
        this.busiAcciDist = busiAcciDist == null ? null : busiAcciDist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_street
     *
     * @return the value of cmd_Business.busi_acci_street
     *
     * @mbggenerated
     */
    public String getBusiAcciStreet() {
        return busiAcciStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_street
     *
     * @param busiAcciStreet the value for cmd_Business.busi_acci_street
     *
     * @mbggenerated
     */
    public void setBusiAcciStreet(String busiAcciStreet) {
        this.busiAcciStreet = busiAcciStreet == null ? null : busiAcciStreet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_id_no
     *
     * @return the value of cmd_Business.busi_acci_id_no
     *
     * @mbggenerated
     */
    public String getBusiAcciIdNo() {
        return busiAcciIdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_id_no
     *
     * @param busiAcciIdNo the value for cmd_Business.busi_acci_id_no
     *
     * @mbggenerated
     */
    public void setBusiAcciIdNo(String busiAcciIdNo) {
        this.busiAcciIdNo = busiAcciIdNo == null ? null : busiAcciIdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_id_type
     *
     * @return the value of cmd_Business.busi_acci_id_type
     *
     * @mbggenerated
     */
    public String getBusiAcciIdType() {
        return busiAcciIdType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_id_type
     *
     * @param busiAcciIdType the value for cmd_Business.busi_acci_id_type
     *
     * @mbggenerated
     */
    public void setBusiAcciIdType(String busiAcciIdType) {
        this.busiAcciIdType = busiAcciIdType == null ? null : busiAcciIdType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_sex
     *
     * @return the value of cmd_Business.busi_acci_sex
     *
     * @mbggenerated
     */
    public String getBusiAcciSex() {
        return busiAcciSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_sex
     *
     * @param busiAcciSex the value for cmd_Business.busi_acci_sex
     *
     * @mbggenerated
     */
    public void setBusiAcciSex(String busiAcciSex) {
        this.busiAcciSex = busiAcciSex == null ? null : busiAcciSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_id_start_date
     *
     * @return the value of cmd_Business.busi_acci_id_start_date
     *
     * @mbggenerated
     */
    public String getBusiAcciIdStartDate() {
        return busiAcciIdStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_id_start_date
     *
     * @param busiAcciIdStartDate the value for cmd_Business.busi_acci_id_start_date
     *
     * @mbggenerated
     */
    public void setBusiAcciIdStartDate(String busiAcciIdStartDate) {
        this.busiAcciIdStartDate = busiAcciIdStartDate == null ? null : busiAcciIdStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_id_end_date
     *
     * @return the value of cmd_Business.busi_acci_id_end_date
     *
     * @mbggenerated
     */
    public String getBusiAcciIdEndDate() {
        return busiAcciIdEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_id_end_date
     *
     * @param busiAcciIdEndDate the value for cmd_Business.busi_acci_id_end_date
     *
     * @mbggenerated
     */
    public void setBusiAcciIdEndDate(String busiAcciIdEndDate) {
        this.busiAcciIdEndDate = busiAcciIdEndDate == null ? null : busiAcciIdEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_birthday
     *
     * @return the value of cmd_Business.busi_acci_birthday
     *
     * @mbggenerated
     */
    public String getBusiAcciBirthday() {
        return busiAcciBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_birthday
     *
     * @param busiAcciBirthday the value for cmd_Business.busi_acci_birthday
     *
     * @mbggenerated
     */
    public void setBusiAcciBirthday(String busiAcciBirthday) {
        this.busiAcciBirthday = busiAcciBirthday == null ? null : busiAcciBirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_acci_payee_rel
     *
     * @return the value of cmd_Business.busi_acci_payee_rel
     *
     * @mbggenerated
     */
    public String getBusiAcciPayeeRel() {
        return busiAcciPayeeRel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_acci_payee_rel
     *
     * @param busiAcciPayeeRel the value for cmd_Business.busi_acci_payee_rel
     *
     * @mbggenerated
     */
    public void setBusiAcciPayeeRel(String busiAcciPayeeRel) {
        this.busiAcciPayeeRel = busiAcciPayeeRel == null ? null : busiAcciPayeeRel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_type
     *
     * @return the value of cmd_Business.busi_type
     *
     * @mbggenerated
     */
    public String getBusiType() {
        return busiType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_type
     *
     * @param busiType the value for cmd_Business.busi_type
     *
     * @mbggenerated
     */
    public void setBusiType(String busiType) {
        this.busiType = busiType == null ? null : busiType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_properties_remark
     *
     * @return the value of cmd_Business.busi_properties_remark
     *
     * @mbggenerated
     */
    public String getBusiPropertiesRemark() {
        return busiPropertiesRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_properties_remark
     *
     * @param busiPropertiesRemark the value for cmd_Business.busi_properties_remark
     *
     * @mbggenerated
     */
    public void setBusiPropertiesRemark(String busiPropertiesRemark) {
        this.busiPropertiesRemark = busiPropertiesRemark == null ? null : busiPropertiesRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_dg_bytes
     *
     * @return the value of cmd_Business.busi_dg_bytes
     *
     * @mbggenerated
     */
    public String getBusiDgBytes() {
        return busiDgBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_dg_bytes
     *
     * @param busiDgBytes the value for cmd_Business.busi_dg_bytes
     *
     * @mbggenerated
     */
    public void setBusiDgBytes(String busiDgBytes) {
        this.busiDgBytes = busiDgBytes == null ? null : busiDgBytes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_medical_insurance
     *
     * @return the value of cmd_Business.busi_medical_insurance
     *
     * @mbggenerated
     */
    public String getBusiMedicalInsurance() {
        return busiMedicalInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_medical_insurance
     *
     * @param busiMedicalInsurance the value for cmd_Business.busi_medical_insurance
     *
     * @mbggenerated
     */
    public void setBusiMedicalInsurance(String busiMedicalInsurance) {
        this.busiMedicalInsurance = busiMedicalInsurance == null ? null : busiMedicalInsurance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_batch_no
     *
     * @return the value of cmd_Business.busi_batch_no
     *
     * @mbggenerated
     */
    public String getBusiBatchNo() {
        return busiBatchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_batch_no
     *
     * @param busiBatchNo the value for cmd_Business.busi_batch_no
     *
     * @mbggenerated
     */
    public void setBusiBatchNo(String busiBatchNo) {
        this.busiBatchNo = busiBatchNo == null ? null : busiBatchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cmd_Business.busi_branch_no
     *
     * @return the value of cmd_Business.busi_branch_no
     *
     * @mbggenerated
     */
    public String getBusiBranchNo() {
        return busiBranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cmd_Business.busi_branch_no
     *
     * @param busiBranchNo the value for cmd_Business.busi_branch_no
     *
     * @mbggenerated
     */
    public void setBusiBranchNo(String busiBranchNo) {
        this.busiBranchNo = busiBranchNo == null ? null : busiBranchNo.trim();
    }
}