package com.loon.mybatis.core.dao;

import com.loon.mybatis.core.pojo.CmdBusiness;

public interface CmdBusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmd_Business
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer busiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmd_Business
     *
     * @mbggenerated
     */
    int insert(CmdBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmd_Business
     *
     * @mbggenerated
     */
    int insertSelective(CmdBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmd_Business
     *
     * @mbggenerated
     */
    CmdBusiness selectByPrimaryKey(Integer busiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmd_Business
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CmdBusiness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cmd_Business
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CmdBusiness record);
}